### ISSUE TITLE
Support spring cloud sleuth

### ISSUE THREAD

**Issue by ipalbeniz** [pivovarit/parallel-collectors#507]
**Is your feature request related to a problem? Please describe.**
I would like to use parallel-collectors in a spring boot application with spring cloud sleuth for tracing requests.
The problem is that the code executed on parallel-collectors loses the request tracing information. I think it happens because `com.pivovarit.collectors.Dispacher` executes the tasks with a `newLazySingleThreadExecutor()` that spring cloud is not able to instrument.

**Describe the solution you'd like**
It would be very helpful if `com.pivovarit.collectors.Dispacher` allows us to configure the `Executor` that runs the tasks instead of creating and using a `newLazySingleThreadExecutor()` that spring cloud sleuth cannot instrument.
I think that spring cloud sleuth is using `org.springframework.cloud.sleuth.instrument.async.TraceableExecutorService` to be able to support tracing in Executors.

**Describe alternatives you've considered**
I've tried to remove the `newLazySingleThreadExecutor()` from `Dispacher` and use the `executor` to execute the tasks. It seems to work properly, but some tests have failed so it seems to be a bad solution.

**Additional context**
I've attached a simple spring boot with spring cloud sleuth application.
[spring-boot-sleuth-parallel-collectors.zip](https://github.com/pivovarit/parallel-collectors/files/5147221/spring-boot-sleuth-parallel-collectors.zip)

Start the application with `./mvnw spring-boot:run`
Go to `http://localhost:8080` in your navigator and check the application logs.

A message is written to the log when transforming some numbers with parallel-collectors, but the spring cloud sleuth "trace-id" is different for every thread:
![Selection_721](https://user-images.githubusercontent.com/7996927/91665684-b2742800-eaf7-11ea-8e01-f0eec0dd1ce3.png)

The expected behavior would be to have the same "trace-id" for every thread:
![Selection_722](https://user-images.githubusercontent.com/7996927/91665741-2adae900-eaf8-11ea-94fa-78a5545415a3.png)

Thank you so much for creating parallel-collectors!

**Comment by pivovarit** [comment]
Thanks for the detailed issue! I need to figure out how Sleuth's instrumentation works and what can we do about it. I will think about it in upcoming days!

**Comment by pivovarit** [comment]
I think that the solution here is to manually fetch the current `TraceContext` and then start a new scope/span inside a function that's getting called by parallel collectors. 

You could use a wrapper like:

```
private <T, R> Function<T, R> withTracing(Function<T, R> f1, TraceContext ctx) {
    return t -> {
        Span span = tracer.nextSpan(TraceContextOrSamplingFlags.newBuilder(ctx).build());
        try (Tracer.SpanInScope scope = tracer.withSpanInScope(span.start())) {
            return f1.apply(t);
        } finally {
            span.finish();
        }
    };
}
```

Then you could just do:

```
TraceContext context = tracer.currentSpan().context();

final List<Integer> integers = IntStream.range(0, 10)
  .boxed()
  .collect(parallel(withTracing(this::transform, context), toList(), this.executor, 2))
  .join();
```

And then you end up with what you wanted:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/2182533/92304545-44a88000-ef7f-11ea-8a2e-2e276b946129.png">

However, each unit of work gets its own span id instead of keeping it per thread.

I'd rather not change the architecture of the library - there's one internal dispatcher thread that delegates the work to the user-provided one. And in order to make it use Spring's automagic, we'd need to either expose it or get rid of it.

I think we could consult @marcingrzejszczak on this one if there's some way in which we could just jump back onto the instrumented executor instead of applying custom span management

**Comment by ipalbeniz** [comment]
Thank you so much for your solution @pivovarit 

For me it is ok to get a different span id for every unit of work so I think that I'll use your solution :smiley:

**Comment by pivovarit** [comment]
Ok, so if that solved your problem then I think we can close this one :)
