### ISSUE TITLE
Make it possible to configure the dispatcher instance in the Dispatcher

### ISSUE THREAD

**Issue by v3rm0n** [pivovarit/parallel-collectors#768]
**Is your feature request related to a problem? Please describe.**
[dispatcher in Dispatcher](https://github.com/pivovarit/parallel-collectors/blob/master/src/main/java/com/pivovarit/collectors/Dispatcher.java#L31) is used to wrap the executor that is passed in which makes it hard to use [Spring Security Concurrency Support](https://docs.spring.io/spring-security/reference/features/integrations/concurrency.html)
**Describe the solution you'd like**
Make it possible to configure the dispatcher implementation (or maybe some other solution that would fix this)

**Describe alternatives you've considered**
I don't see any alternatives

**Additional context**
The default (and recommended) implementation of security context holder strategy uses thread locals to keep track of the current security context so by default it doesn't get passed on to code executing in the threadpools so that's where the concurrency support comes in: it injects the security context from the current thread to the new one.
So when we use parallel-collectors, the security context is passed on to the dispatcher thread which does not pass it on to the executor thread.

**Comment by pivovarit** [comment]
Hmm, that's definitely a valid issue. Let me think about the best solution.

**Comment by v3rm0n** [comment]
One solution would be to make the ThreadFactory implementation on the dispatcher configurable, maybe as a static field on the Dispatcher. Passing it in would be an option as well with method overloads, but it would make the API more complex...

**Comment by pivovarit** [comment]
Sorry for making you wait, but I wanted to find an ultimate solution instead of patchwork. The easiest solution seems to be Reactor-style static wrappers (think `Hooks.wrapQueue()`), but that would be naturally class-scoped and could lead to some funky issues when dealing with the magical land of class loading.

Instead, I came up with an ultimate solution which involves redoing the architecture so that `Dispatcher` does not need to rely on a dedicated single-thread `Executor` - caller thread can do this work by itself:
- https://github.com/pivovarit/parallel-collectors/pull/789

I still need to do my due diligence when it comes to potential impact when introducing such change in a minor release, but I feel like this is the way to go

**Comment by pivovarit** [comment]
An update here: I revisited the internal design and completely eliminated that extra dispatcher thread, which means this no longer be an issue. I will release this as part of `2.6.0` and `3.0.0`

**Comment by pivovarit** [comment]
https://github.com/pivovarit/parallel-collectors/releases/tag/2.6.0
